-- Apply once with scripts/booking-db.ps1 schema. No DROP, ALTER or data replacement.
-- Oracle DDL commits implicitly: on a partial failure inspect, do not delete or rerun blindly.
DECLARE
  object_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO object_count FROM user_objects
  WHERE object_name IN ('BKG_SPACE', 'BKG_BOOKING', 'BKG_SPACE_SEQ', 'BKG_BOOKING_SEQ',
                        'BKG_BOOKING_SPACE_TIME_IX', 'BKG_BOOKING_OWNER_IX');
  IF object_count <> 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'BKG objects already exist: inspect before applying V001');
  END IF;
END;
/
CREATE SEQUENCE BKG_SPACE_SEQ START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE BKG_BOOKING_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE BKG_SPACE (
  ID NUMBER(19) NOT NULL,
  NAME VARCHAR2(120 CHAR) NOT NULL,
  SPACE_TYPE VARCHAR2(20 CHAR) NOT NULL,
  CAPACITY NUMBER(10) NOT NULL,
  SITE VARCHAR2(160 CHAR) NOT NULL,
  CONSTRAINT BKG_SPACE_PK PRIMARY KEY (ID),
  CONSTRAINT BKG_SPACE_TYPE_CK CHECK (SPACE_TYPE IN ('ROOM','AUDITORIUM','COWORKING')),
  CONSTRAINT BKG_SPACE_CAPACITY_CK CHECK (CAPACITY > 0)
);
CREATE TABLE BKG_BOOKING (
  ID NUMBER(19) NOT NULL,
  SPACE_ID NUMBER(19) NOT NULL,
  OWNER_ID VARCHAR2(100 CHAR) NOT NULL,
  STARTS_AT TIMESTAMP(9) WITH TIME ZONE NOT NULL,
  ENDS_AT TIMESTAMP(9) WITH TIME ZONE NOT NULL,
  STATUS VARCHAR2(12 CHAR) NOT NULL,
  CONSTRAINT BKG_BOOKING_PK PRIMARY KEY (ID),
  CONSTRAINT BKG_BOOKING_SPACE_FK FOREIGN KEY (SPACE_ID) REFERENCES BKG_SPACE(ID),
  CONSTRAINT BKG_BOOKING_STATUS_CK CHECK (STATUS IN ('ACTIVE','CANCELLED')),
  CONSTRAINT BKG_BOOKING_RANGE_CK CHECK (STARTS_AT < ENDS_AT)
);
CREATE INDEX BKG_BOOKING_SPACE_TIME_IX ON BKG_BOOKING (SPACE_ID, STATUS, STARTS_AT, ENDS_AT);
CREATE INDEX BKG_BOOKING_OWNER_IX ON BKG_BOOKING (OWNER_ID, STATUS, ENDS_AT);
