spring.application.name=booking
spring.config.import=configtree:/run/secrets/
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${JDBC_USER}
spring.datasource.password=${app_password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.sql.init.mode=never
